#
# flankfasta configuration file
#

#==========================================
# system variables
# (uncomment to edit the following section)

# user identifiers
#user:
  #email:     user@example.com

# system-dependent configuration
system:
  # number of CPUs (default = 1)
  #cpus:   2
  # required binaries naming
  tcoffee:   t_coffee
  gblocks:   gblocks


#==========================================
# pipeline variables
# (uncomment to edit the following section)

# source alignmen files' directories
#directories:
  #nucleic:   nucleic_acid_seq_directory
  #amino:     amino_acid_seq_directory

# GBlocks minimum length of a block (default = 5)
#gblocks_opt:
  #amin_block:    10
  #nucl_block:    10
